Giants Configuration:
  Giant Stats:
    Experience: 5
    Health: 100
    Fire Attack:
      Enabled: false
      Ticks for Target: 100
      Ticks for Giant: 100
    Spawn Worlds:
    Drops:
    - '1:0:1'
  Spawn Settings:
    Spawn Chance: 10
    Biomes:
      Forest: false
      Desert: true
      Plains: true
      Swampland: true
      Jungle: false
      Ice Plains: false
      Taiga: false
      Extreme Hills: true
      Ice Mountains: false
      Mushroom Island: true
  Debug Mode: true
  Language:
    Debug Message: '&2A Giant has spawned! X:&F%X &2Y:&F%Y &2Z:&F%Z'