Giants Configuration:
  Giant Stats:
    Health: 100
    Experience: 5
    Drops:
  Spawn Settings:
    Chance: 10
    Worlds:
    Biomes:
      Forest: false
      Desert: true
      Plains: true
      Swampland: true
      Jungle: false
      Ice Plains: false
      Taiga: false
      Extreme Hills: true
      Ice Mountains: false
      Mushroom Island: true
      Other: true
  Attack Mechanisms:
    Lightning Attack: false
    Throw Boulder Attack: false
    Stomp Attack: false
    Kick Attack:
      Enabled: false
      Kick Height: 1
    Fire Attack:
      Enabled: false
      Ticks for Target: 100
      Ticks for Giant: 100
    Spawn Zombies Attack:
      Enabled: false
      Zombies to Spawn: 5
  Sounds:
    Fire Attack: true
    Throw Boulder Attack: true
    Kick Attack: true
    Death: true
  Otional Dependencies:
    Spout: true
  Debug Mode: false
  Language:
    Debug Message: '&2A Giant has spawned at X:&F%X &2Y:&F%Y &2Z:&F%Z'